### ISSUE TITLE
Fix github workflow once Unity support Linux

### ISSUE THREAD

**Issue by louis030195** [louis030195/niwrad#2]
## Is your feature request related to a problem? Please describe

Unity doesn't support Linux https://github.com/webbertakken/unity-actions/issues/84

## Describe the solution you'd like

Push -> Github page offline scene WebGL

## Describe alternatives you've considered

Build WebGL somehow and push manually

**Comment by GabLeRoux** [comment]
> Unity doesn't support Linux
Can you be more specific? Do you mean Docker?

**Comment by louis030195** [comment]
@GabLeRoux yeah, i mean I've been using unity on Linux for years, always issues, I can barely compile anything locally even with UI and the trick nographics with docker only fix tests in my case, build still broken

**Comment by louis030195** [comment]
Might be caused by OpenGL stuff https://github.com/louis030195/niwrad/blob/49c15c12247fa58089ba4661f41b812cdf77dff2/Assets/Scripts/Player/UnitSelection.cs#L171

**Comment by louis030195** [comment]
downgrade to 2019.1.4f1 fixed the issue
